version: '3'
services:
  api:
    build:
      context: .
      dockerfile: /etc/api/Dockerfile
    links:
      - database
    ports:
      - "8080:8080"
    depends_on:
      - "database"

  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"